// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessages.proto

package panda.core;

public final class TestMessages {
  private TestMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 sender_time_Stamp = 1;
    /**
     * <code>required uint64 sender_time_Stamp = 1;</code>
     */
    boolean hasSenderTimeStamp();
    /**
     * <code>required uint64 sender_time_Stamp = 1;</code>
     */
    long getSenderTimeStamp();

    // optional uint64 sender_seq_num = 2;
    /**
     * <code>optional uint64 sender_seq_num = 2;</code>
     */
    boolean hasSenderSeqNum();
    /**
     * <code>optional uint64 sender_seq_num = 2;</code>
     */
    long getSenderSeqNum();
  }
  /**
   * Protobuf type {@code panda.core.TestMessage}
   */
  public static final class TestMessage extends
      com.google.protobuf.GeneratedMessage
      implements TestMessageOrBuilder {
    // Use TestMessage.newBuilder() to construct.
    private TestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestMessage defaultInstance;
    public static TestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              senderTimeStamp_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              senderSeqNum_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return panda.core.TestMessages.internal_static_panda_core_TestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return panda.core.TestMessages.internal_static_panda_core_TestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              panda.core.TestMessages.TestMessage.class, panda.core.TestMessages.TestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestMessage>() {
      public TestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 sender_time_Stamp = 1;
    public static final int SENDER_TIME_STAMP_FIELD_NUMBER = 1;
    private long senderTimeStamp_;
    /**
     * <code>required uint64 sender_time_Stamp = 1;</code>
     */
    public boolean hasSenderTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 sender_time_Stamp = 1;</code>
     */
    public long getSenderTimeStamp() {
      return senderTimeStamp_;
    }

    // optional uint64 sender_seq_num = 2;
    public static final int SENDER_SEQ_NUM_FIELD_NUMBER = 2;
    private long senderSeqNum_;
    /**
     * <code>optional uint64 sender_seq_num = 2;</code>
     */
    public boolean hasSenderSeqNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 sender_seq_num = 2;</code>
     */
    public long getSenderSeqNum() {
      return senderSeqNum_;
    }

    private void initFields() {
      senderTimeStamp_ = 0L;
      senderSeqNum_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSenderTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, senderTimeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, senderSeqNum_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, senderTimeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, senderSeqNum_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static panda.core.TestMessages.TestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static panda.core.TestMessages.TestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static panda.core.TestMessages.TestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static panda.core.TestMessages.TestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(panda.core.TestMessages.TestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code panda.core.TestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements panda.core.TestMessages.TestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return panda.core.TestMessages.internal_static_panda_core_TestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return panda.core.TestMessages.internal_static_panda_core_TestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                panda.core.TestMessages.TestMessage.class, panda.core.TestMessages.TestMessage.Builder.class);
      }

      // Construct using panda.core.TestMessages.TestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        senderTimeStamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        senderSeqNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return panda.core.TestMessages.internal_static_panda_core_TestMessage_descriptor;
      }

      public panda.core.TestMessages.TestMessage getDefaultInstanceForType() {
        return panda.core.TestMessages.TestMessage.getDefaultInstance();
      }

      public panda.core.TestMessages.TestMessage build() {
        panda.core.TestMessages.TestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public panda.core.TestMessages.TestMessage buildPartial() {
        panda.core.TestMessages.TestMessage result = new panda.core.TestMessages.TestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.senderTimeStamp_ = senderTimeStamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.senderSeqNum_ = senderSeqNum_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof panda.core.TestMessages.TestMessage) {
          return mergeFrom((panda.core.TestMessages.TestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(panda.core.TestMessages.TestMessage other) {
        if (other == panda.core.TestMessages.TestMessage.getDefaultInstance()) return this;
        if (other.hasSenderTimeStamp()) {
          setSenderTimeStamp(other.getSenderTimeStamp());
        }
        if (other.hasSenderSeqNum()) {
          setSenderSeqNum(other.getSenderSeqNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSenderTimeStamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        panda.core.TestMessages.TestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (panda.core.TestMessages.TestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 sender_time_Stamp = 1;
      private long senderTimeStamp_ ;
      /**
       * <code>required uint64 sender_time_Stamp = 1;</code>
       */
      public boolean hasSenderTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 sender_time_Stamp = 1;</code>
       */
      public long getSenderTimeStamp() {
        return senderTimeStamp_;
      }
      /**
       * <code>required uint64 sender_time_Stamp = 1;</code>
       */
      public Builder setSenderTimeStamp(long value) {
        bitField0_ |= 0x00000001;
        senderTimeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 sender_time_Stamp = 1;</code>
       */
      public Builder clearSenderTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        senderTimeStamp_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 sender_seq_num = 2;
      private long senderSeqNum_ ;
      /**
       * <code>optional uint64 sender_seq_num = 2;</code>
       */
      public boolean hasSenderSeqNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 sender_seq_num = 2;</code>
       */
      public long getSenderSeqNum() {
        return senderSeqNum_;
      }
      /**
       * <code>optional uint64 sender_seq_num = 2;</code>
       */
      public Builder setSenderSeqNum(long value) {
        bitField0_ |= 0x00000002;
        senderSeqNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sender_seq_num = 2;</code>
       */
      public Builder clearSenderSeqNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        senderSeqNum_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:panda.core.TestMessage)
    }

    static {
      defaultInstance = new TestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:panda.core.TestMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_panda_core_TestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_panda_core_TestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TestMessages.proto\022\npanda.core\"@\n\013Test" +
      "Message\022\031\n\021sender_time_Stamp\030\001 \002(\004\022\026\n\016se" +
      "nder_seq_num\030\002 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_panda_core_TestMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_panda_core_TestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_panda_core_TestMessage_descriptor,
              new java.lang.String[] { "SenderTimeStamp", "SenderSeqNum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
